source 'https://rubygems.org'

gem 'guard'
gem 'guard-shell'
gem 'rb-inotify'
gem 'guard-livereload', '>= 2.5.2'
gem 'yajl-ruby', '>= 1.3.1'
gem 'asciidoctor', '~> 0.1.4'
gem 'tilt'
gem 'slim'
gem 'rb-readline'
